server:
  port: 9443

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: user
      password: password

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
